---
- name: Create apt autoremove service
  copy:
    src: ./files/apt-autoremove.service.j2
    dest: /etc/systemd/system/apt-autoremove.service
    owner: root
    group: root
    mode: 0644
  notify: Enable apt-autoremove service

- name: Create apt autoremove timer
  copy:
    src: ./files/apt-autoremove.timer.j2
    dest: /etc/systemd/system/apt-autoremove.timer
    owner: root
    group: root
    mode: 0644
  notify: Start apt-autoremove timer
