---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-aptsettings-noble
    box: cloud-image/ubuntu-24.04
  - name: ansible-aptsettings-jammy
    box: cloud-image/ubuntu-22.04
  - name: ansible-aptsettings-focal
    box: cloud-image/ubuntu-20.04
  - name: ansible-aptsettings-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: ansible-aptsettings-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
